use_frameworks!
workspace 'DI_Playground'

target 'DIPods' do
  project 'DIPods/DIPods.xcodeproj'
  pod 'Swinject', '~> 2.0'
end

post_install do |installer_representation|
installer_representation.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
    config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
