source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'Contacts' do
  platform :ios, '9.0'
#  pod 'Moya'
  pod 'SnapKit'
  pod 'RealmSwift'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxRealm'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.name == 'Debug'
        config.build_settings['ENABLE_TESTABILITY'] = 'YES'
        config.build_settings['SWIFT_VERSION'] = '3.0'
      end
    end
  end
end
